# Generated by Django 4.1.5 on 2023-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='vote',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
