# Generated by Django 4.1.5 on 2023-06-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_rate_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
