# Generated by Django 4.2.2 on 2023-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='movie_title',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
