# Generated by Django 4.2.2 on 2023-06-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_alter_favourite_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='movie_image',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='movie_title',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
