# Generated by Django 4.2.2 on 2023-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_favourite_movie_image_alter_favourite_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='movie_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='username',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
